steps:
  - id: "build image"
    name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/${PROJECT_ID}/${_SERVICE_NAME}", "-f", "Dockerfile.prod", "."]

  - id: "push image"
    name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/${PROJECT_ID}/${_SERVICE_NAME}"]

  - id: "deploy to cloud run"
    name: "gcr.io/cloud-builders/gcloud"
    args: ["run", "services", "update", "--image", "gcr.io/${PROJECT_ID}/${_SERVICE_NAME}", "--region", "${_REGION}",  "${_SERVICE_NAME}" ]

substitutions:
  #  _INSTANCE_NAME: bob-backend
  _REGION: europe-north1
  _SERVICE_NAME: bob-frontend

images:
  - "gcr.io/${PROJECT_ID}/${_SERVICE_NAME}"