FROM node:16.17.1-alpine3.16 as build
COPY ./app /app
WORKDIR /app
RUN npm install

RUN npx vite build

FROM nginx:1.23.3
COPY --from=build /app/dist/ /usr/share/nginx/html
COPY ./nginx.conf /etc/nginx/conf.d/default.conf