steps:
- name: "gcr.io/cloud-builders/docker"
  args: ["build", "-t", "gcr.io/$PROJECT_ID/bob_prod:$COMMIT_SHA", "."]
  env: ["VITE_PUBLIC_KEY=$_VITE_PUBLIC_KEY", "VITE_SERVICE_ID=$_VITE_SERVICE_ID", "VITE_TEMPLATE_ID=$_VITE_TEMPLATE_ID"]
- name: "gcr.io/cloud-builders/docker"
  args: ["push", "gcr.io/$PROJECT_ID/bob_prod:$COMMIT_SHA"]
- name: "gcr.io/cloud-builders/gcloud"
  args: ["run", "deploy", "bob", "--image", "gcr.io/$PROJECT_ID/bob_prod:$COMMIT_SHA", "--region", "$_DEPLOY_REGION", "--allow-unauthenticated", "--platform", "$_PLATFORM"]
  env: ["CLOUDSDK_COMPUTE_ZONE=$_DEPLOY_REGION"]
  env: ["CLOUDSDK_CONTAINER_USE_CLIENT_CERTIFICATE=True"]

timeout: "600s"